### ISSUE TITLE
接的任務的show 畫面歪了嘞

### ISSUE THREAD

**Issue by nauosika** [LegRow/row_leg#237]

**Comment by nauosika** [comment]
<img width="561" alt="截圖 2021-05-28 下午3 49 14" src="https://user-images.githubusercontent.com/79121183/119949409-6d205080-bfcc-11eb-96ae-d304a2ace7e7.png">

**Comment by huihsinhsiao** [comment]
and 地圖位置需要調整
![image](https://user-images.githubusercontent.com/77479612/119996272-213bce80-c001-11eb-9f40-e1af33ebdfa6.png)
