### ISSUE TITLE
任務卡片，須根據狀態改變

### ISSUE THREAD

**Issue by nauosika** [LegRow/row_leg#252]
<img width="403" alt="截圖 2021-05-30 下午3 54 35" src="https://user-images.githubusercontent.com/79121183/120096670-68d86c80-c15f-11eb-8ed9-c40311fd4c24.png">
好像示範有這個 比較好講

**Comment by huihsinhsiao** [comment]
列表頁呈現所有卡片 (不同狀態的卡片) 時，需要明確的狀態樣式 (ex. 已結束 or 尚未開始)
範例：
![image](https://user-images.githubusercontent.com/77479612/120177188-b83f9b00-c23a-11eb-8ac8-7bbc54dd08b0.png)

**Comment by huihsinhsiao** [comment]
與 #263 重複
